---
title: "Beer Study"
author: "Katon Pang"
date: "11/7/2023"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE}

library(shiny)

ui <- fluidPage(
  
  # App title ----
  titlePanel("Beer Study"),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      
      # file upload manager
      fileInput("file", label = h3("File input"), accept = ".csv"),
  
      hr(),
      fluidRow(column(4, verbatimTextOutput("value"))),
      
      #Input: Slider for the number of bins ----
      sliderInput(inputId = "bins",
                  label = "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30),
      
      #Copy the line below to make a select box 
      selectInput("select", label = h3("Histogram or Boxplot"), 
                  choices = list("Histogram" = "histogram", 
                                 "Boxplot" = "boxplot"), selected = 1),
      hr(),
      fluidRow(column(3, verbatimTextOutput("value")))
      
      # Copy the chunk below to make a group of checkboxes
      # checkboxGroupInput("checkGroup", label = h3("Select State(s):"), 
      # choices = list("Choice 1" = 1, "Choice 2" = 2, "Choice 3" = 3),
      # selected = 1),
      # 
      # hr(),
      # fluidRow(column(3, verbatimTextOutput("value")))
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      plotOutput(outputId = "distPlot")
      
    )
  )
)


# Define server logic required to draw a histogram ----
server <- function(input, output, session) {
  
  data <- reactive({
    req(input$file)
   
  })
  
  file = input$file
  
  beer = read.csv(file$datapath)
  
  # You can access the value of the widget with input$file, e.g.
  output$value <- renderPrint({
    str(input$file)
  })
  
  
  # You can access the values of the widget (as a vector)
  # with input$checkGroup, e.g.
  #output$value <- renderPrint({ input$checkGroup })
  
  # Histogram of IBU
  output$distPlot <- renderPlot({
    
    if(input$select == "histogram")
    {
    x    <- beer$IBU
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    
    hist(x, breaks = bins, col = "#75AADB", border = "white",
         xlab = "IBU",
         main = "Histogram of IBU")
    }
    if(input$select == "boxplot")
    {
    x    <- beer$IBU
    
    boxplot(x, width = 0.5, col = "white", border = "#75AADB",
         xlab = "IBU",
         main = "Boxplot of IBU")
    }
  })
  
}

shinyApp(ui, server)

```
